<?php

// Require the autoload file generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

error_reporting(E_ALL);
ini_set('display_errors', 1);


// Create an instance of the Mpdf\Mpdf class
$mpdf = new \Mpdf\Mpdf;

// Load HTML content from an external file
$htmlFilePath = __DIR__ . '/print-templates/print-older-persons.html';
$htmlContent = file_get_contents($htmlFilePath);

// Check if the file was loaded successfully
if ($htmlContent === false) {
    die('Error loading the HTML template.');
}

// Write the HTML content to the PDF
$mpdf->WriteHTML($htmlContent);

// Output the PDF to a file
$mpdf->Output('example.pdf', 'I');

?>